"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Tuple, Union
from typing_extensions import Literal
from pydantic.fields import FieldInfo

PYDANTIC_V2 = ...
if PYDANTIC_V2:
    def use_pydantic_2_plus(): # -> Literal[True]:
        ...
    
    @dataclass
    class ModelField:
        field_info: FieldInfo
        name: str
        mode: Literal["validation", "serialization"] = ...
        @property
        def alias(self) -> str:
            ...
        
        @property
        def required(self) -> bool:
            ...
        
        @property
        def default(self) -> Any:
            ...
        
        @property
        def type_(self) -> Any:
            ...
        
        def __post_init__(self) -> None:
            ...
        
        def get_default(self) -> Any:
            ...
        
        def validate(self, value: Any, values: Dict[str, Any] = ..., *, loc: Tuple[Union[int, str], ...] = ...) -> Tuple[Any, Union[List[Dict[str, Any]], None]]:
            ...
        
        def __hash__(self) -> int:
            ...
        
    
    
else:
    def use_pydantic_2_plus(): # -> Literal[False]:
        ...
    
